  library(shiny)
  library(readxl)
  library(sf)
  library(leaflet)
  library(leaflet.extras)
  library(htmltools)
  library(tidyverse)
  library(RColorBrewer)
  #setwd("H:/Finance/R/Project R/Shp file Sweden/Shiny_Sweden")
  load("SHP_Kommun_Befolk.Rdata")
  # KOM_BEF$Y_2019 <- as.character(KOM_BEF$Y_2019)
  # KOM_BEF$Flyttningsnetto <- as.character(KOM_BEF$Flyttningsnetto)
  # KOM_BEF$Y_2019 <- as.numeric(KOM_BEF$Y_2019)
  # KOM_BEF$Flyttningsnetto <- as.numeric(KOM_BEF$Flyttningsnetto)
  # sapply(KOM_BEF, class)
#   KOM_BEF$Y_2019 <- unname(KOM_BEF$Y_2019)    ##### Remove Named num tag
#   KOM_BEF$Flyttningsnetto  <- unname(KOM_BEF$Flyttningsnetto)
#   KOM_BEF$Y_2019 <- sapply(KOM_BEF$Y_2019, as.numeric)
#   save(KOM_BEF, file = "SHP_Kommun_Befolk.Rdata")
#   KOM_BEF$Flyttningsnetto  <- sapply(KOM_BEF$Flyttningsnetto, as.numeric)
#   # sapply(KOM_BEF, class)
# str(KOM_BEF)
